language: generic
sudo: true

services:
  - docker

env:
  matrix:
    - TAG=v0.10.x
    - TAG=v0.12.x
    - TAG=v4.2.x
    - TAG=v4.3.x
    - TAG=v4.4.x
    - TAG=v4.5.x
    - TAG=v4.6.x
    - TAG=v6.1.x
    - TAG=v6.11.x
    - TAG=v6.2.x
    - TAG=v6.3.x
    - TAG=v6.4.x
    - TAG=v6.7.x
    - TAG=v6.9.x
    - TAG=v8.1.x
    - TAG=v8.2.x

script:
  - make build
  - make test

before_deploy:
  - export DOCKER_CONFIG="${HOME}/.docker"
  - mkdir -p "$DOCKER_CONFIG"
  - openssl aes-256-cbc -K "$DOCKER_CONF_key" -iv "$DOCKER_CONF_iv" -in .docker/config.json.enc -out "${DOCKER_CONFIG}/config.json" -d

deploy:
  provider: script
  skip_cleanup: true
  script: make push
  on:
    branch: master
